"""add trace headers to outbox events

Revision ID: 131307314ffc
Revises: 99492a94d738
Create Date: 2026-08-04 12:50:02.481450

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '131307314ffc'
down_revision: Union[str, None] = '99492a94d738'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # server_default so this is safe to add NOT NULL against a table that
    # already has rows (existing rows get '{}', matching the ORM-side
    # default for any new row inserted without going through write_outbox_event).
    op.add_column(
        'outbox_events',
        sa.Column('trace_headers', sa.JSON(), nullable=False, server_default='{}'),
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('outbox_events', 'trace_headers')
    # ### end Alembic commands ###
