"""add insights table

Revision ID: 99492a94d738
Revises: e003053fae26
Create Date: 2026-08-03 09:35:27.555272

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '99492a94d738'
down_revision: Union[str, None] = 'e003053fae26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('insights',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_insights_user_id'), 'insights', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_insights_user_id'), table_name='insights')
    op.drop_table('insights')
    # ### end Alembic commands ###
