"""add institutions and plaid account linking columns

Revision ID: a6e541028954
Revises: 8d102e87b663
Create Date: 2026-08-02 20:29:36.020775

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'a6e541028954'
down_revision: Union[str, None] = '8d102e87b663'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('institutions',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('plaid_item_id', sa.String(length=255), nullable=False),
    sa.Column('plaid_institution_id', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('access_token_ciphertext', sa.LargeBinary(), nullable=False),
    sa.Column('status', sa.Enum('active', 'error', 'revoked', name='institution_status'), nullable=False),
    sa.Column('transactions_cursor', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_institutions_plaid_item_id'), 'institutions', ['plaid_item_id'], unique=True)
    op.create_index(op.f('ix_institutions_user_id'), 'institutions', ['user_id'], unique=False)
    op.add_column('accounts', sa.Column('institution_id', sa.Uuid(), nullable=True))
    op.add_column('accounts', sa.Column('plaid_account_id', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_accounts_institution_id'), 'accounts', ['institution_id'], unique=False)
    op.create_index(op.f('ix_accounts_plaid_account_id'), 'accounts', ['plaid_account_id'], unique=True)
    op.create_foreign_key('fk_accounts_institution_id_institutions', 'accounts', 'institutions', ['institution_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_accounts_institution_id_institutions', 'accounts', type_='foreignkey')
    op.drop_index(op.f('ix_accounts_plaid_account_id'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_institution_id'), table_name='accounts')
    op.drop_column('accounts', 'plaid_account_id')
    op.drop_column('accounts', 'institution_id')
    op.drop_index(op.f('ix_institutions_user_id'), table_name='institutions')
    op.drop_index(op.f('ix_institutions_plaid_item_id'), table_name='institutions')
    op.drop_table('institutions')
    # Postgres native ENUM types outlive DROP TABLE — see the same fix
    # (and explanation) in the Phase 3 migration's downgrade().
    op.execute('DROP TYPE IF EXISTS institution_status')
    # ### end Alembic commands ###
