"""add alerts table

Revision ID: e003053fae26
Revises: c409e66dd71b
Create Date: 2026-08-03 08:41:18.388963

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'e003053fae26'
down_revision: Union[str, None] = 'c409e66dd71b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alerts',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('alert_type', sa.Enum('duplicate_charge', 'spend_spike', 'subscription_price_increase', name='alert_type'), nullable=False),
    sa.Column('severity', sa.Enum('info', 'warning', 'critical', name='alert_severity'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('related_transaction_id', sa.Uuid(), nullable=True),
    sa.Column('source_event_id', sa.Uuid(), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['related_transaction_id'], ['transactions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_event_id', 'alert_type', name='uq_alerts_source_event_id_alert_type')
    )
    op.create_index(op.f('ix_alerts_source_event_id'), 'alerts', ['source_event_id'], unique=False)
    op.create_index(op.f('ix_alerts_user_id'), 'alerts', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_alerts_user_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_source_event_id'), table_name='alerts')
    op.drop_table('alerts')
    # ### end Alembic commands ###
    # Postgres native ENUM types outlive DROP TABLE — see the same fix
    # in the Phase 3 and Phase 6 migrations' downgrade().
    op.execute('DROP TYPE IF EXISTS alert_type')
    op.execute('DROP TYPE IF EXISTS alert_severity')
