{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "core-api.fullname" . }}
  labels:
    {{- include "core-api.labels" . | nindent 4 }}
  {{- if .Values.serviceAccount.eksRoleArn }}
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.serviceAccount.eksRoleArn }}
  {{- end }}
{{- end }}
